import streamlit as st

from prediction import predict_loan
from explain import get_reasons
from llm import generate_report
from human_loop import human_decision

from fpdf import FPDF
from datetime import datetime
from pdf_utils import analyze_pdf


# -----------------------------
# PAGE CONFIG
# -----------------------------

st.set_page_config(
    page_title="AI Loan Approval Copilot",
    page_icon="🏦",
    layout="wide"
)


# -----------------------------
# SESSION HISTORY
# -----------------------------

if "loan_history" not in st.session_state:
    st.session_state.loan_history = []


st.title("🏦 AI Loan Approval Co-Pilot")


# -----------------------------
# INPUT SECTION
# -----------------------------

customer_name = st.text_input(
    "Customer Name"
)


gender = st.selectbox(
    "Gender",
    ["Male","Female"]
)


married = st.selectbox(
    "Married",
    ["Yes","No"]
)


dependents = st.number_input(
    "Dependents",
    min_value=0,
    max_value=3
)


education = st.selectbox(
    "Education",
    [
        "Graduate",
        "Not Graduate"
    ]
)


self_employed = st.selectbox(
    "Self Employed",
    [
        "Yes",
        "No"
    ]
)


income = st.number_input(
    "Applicant Income",
    min_value=1,
    max_value=81000
)


co_income = st.number_input(
    "Co Applicant Income",
    min_value=0,
    max_value=41667
)


loan = st.number_input(
    "Loan Amount",
    min_value=1,
    max_value=700
)


term = st.number_input(
    "Loan Term",
    min_value=1,
    max_value=480
)


credit = st.selectbox(
    "Credit History",
    [1,0]
)


area = st.selectbox(
    "Property Area",
    [
        "Urban",
        "Semiurban",
        "Rural"
    ]
)



pdf = st.file_uploader(
    "Upload Salary Slip",
    type=["pdf"]
)


if pdf:

    result = analyze_pdf(pdf)


    st.subheader("PDF Information")


    st.write(
        "Company:",
        result["company"]
    )


    st.write(
        "Salary:",
        result["salary"]
    )


    st.text_area(
        "Extracted Text",
        result["raw_text"],
        height=300
    )

# -----------------------------
# PDF FUNCTION
# -----------------------------

def clean_text(text):

    return str(text).encode(
        "ascii",
        "ignore"
    ).decode()



def create_pdf(
    name,
    prediction,
    confidence,
    reasons,
    decision
):

    pdf = FPDF()

    pdf.add_page()


    pdf.set_font(
        "Arial",
        "B",
        16
    )


    pdf.cell(
        0,
        10,
        "AI Loan Approval Report",
        ln=True,
        align="C"
    )


    pdf.ln(10)


    pdf.set_font(
        "Arial",
        size=12
    )


    pdf.cell(
        0,
        10,
        clean_text(f"Customer Name: {name}"),
        ln=True
    )


    pdf.cell(
        0,
        10,
        clean_text(f"Prediction: {prediction}"),
        ln=True
    )


    pdf.cell(
        0,
        10,
        clean_text(
            f"Confidence: {confidence:.2f}%"
        ),
        ln=True
    )


    pdf.cell(
        0,
        10,
        clean_text(
            f"Officer Decision: {decision}"
        ),
        ln=True
    )


    pdf.cell(
        0,
        10,
        f"Date: {datetime.now().strftime('%d-%m-%Y')}",
        ln=True
    )


    pdf.ln(10)


    pdf.set_font(
        "Arial",
        "B",
        12
    )


    pdf.cell(
        0,
        10,
        "AI Explanation:",
        ln=True
    )


    pdf.set_font(
        "Arial",
        size=11
    )


    for r in reasons:

        pdf.multi_cell(
            0,
            8,
            clean_text("- " + r)
        )


    pdf.ln(10)


    pdf.cell(
        0,
        10,
        "Generated by AI Loan Copilot",
        ln=True,
        align="C"
    )


    file = "Loan_Report.pdf"


    pdf.output(file)


    return file



# -----------------------------
# ANALYZE BUTTON
# -----------------------------

if st.button("🔍 Analyze Loan"):


    user_data = {


        "Gender": gender,

        "Married": married,

        "Dependents": dependents,

        "Education": education,

        "Self_Employed": self_employed,

        "ApplicantIncome": income,

        "CoapplicantIncome": co_income,

        "LoanAmount": loan,

        "Loan_Amount_Term": term,

        "Credit_History": credit,

        "Property_Area": area

    }



    result, confidence, processed, preprocessor = predict_loan(
        user_data
    )



    # Save History

    st.session_state.loan_history.append(

        {

            "Customer": customer_name,

            "Prediction": result,

            "Confidence": confidence

        }

    )



    reasons = get_reasons(
        user_data
    )



    report = generate_report(
        result,
        confidence,
        reasons
    )



    decision = human_decision()



    # -----------------------------
    # DASHBOARD
    # -----------------------------


    st.divider()


    st.header(
        "📊 Loan Decision Dashboard"
    )



    approved = len(

        [

            x for x in st.session_state.loan_history

            if x["Prediction"] == "Loan Approved"

        ]

    )


    rejected = len(

        [

            x for x in st.session_state.loan_history

            if x["Prediction"] == "Loan Rejected"

        ]

    )


    total = len(
        st.session_state.loan_history
    )



    c1,c2,c3 = st.columns(3)


    with c1:

        st.metric(
            "Total Applications",
            total
        )


    with c2:

        st.metric(
            "Approved Loans",
            approved
        )


    with c3:

        st.metric(
            "Rejected Loans",
            rejected
        )



    st.divider()



    col1,col2,col3 = st.columns(3)



    with col1:

        st.metric(
            "Customer",
            customer_name
        )


    with col2:

        st.metric(
            "Confidence",
            f"{confidence:.2f}%"
        )


    with col3:

        if result == "Loan Approved":

            st.success(
                "APPROVED"
            )

        else:

            st.error(
                "REJECTED"
            )



    st.subheader(
        "🤖 AI Explanation"
    )


    for r in reasons:

        st.write(
            "•",
            r
        )



    st.subheader(
        "📝 AI Report"
    )


    st.info(
        report
    )



    st.subheader(
        "👨‍💼 Officer Decision"
    )


    st.write(
        decision
    )



    # -----------------------------
    # PDF DOWNLOAD
    # -----------------------------


    pdf_file = create_pdf(

        customer_name,

        result,

        confidence,

        reasons,

        decision

    )



    with open(pdf_file,"rb") as f:


        st.download_button(

            label="📄 Download Report",

            data=f,

            file_name="Loan_Report.pdf",

            mime="application/pdf"

        )